### ISSUE TITLE
[RECORDING] Rachel: Contractions/General Flow of app

### ISSUE THREAD

**Issue by Shrenil19** [Shrenil19/BrainyPhonics#42]
Recording from the main menu page navigating to a contractions slide deck, showing full functionality of clicking through the slides back and forth with sound effects if there are any. Should be 15-20 seconds. Please record highest quality as possible (min 720p).

Set Up:  Please record with the attached image set as your desktop Background or have the image opened up in the background covering all other applications on your computer. Please close all other applications except the emulator and optionally the android studio. (Leave android studio open if you wish to show the CLI output while the program is running if its relevant to your features.

Here is an example of what it should look close to: https://youtu.be/TgHwfl0f_7E [https://youtu.be/TgHwfl0f_7E](url)

![Screen Shot 2021-04-02 at 4.53.04 PM.png](https://images.zenhubusercontent.com/6011f2a9a91eae7cd6b405e5/c53ea2ae-95eb-40e4-960d-28214611bd67)

Wallpaper Link: https://wallpapercave.com/wp/wp2237402.jpg
![wp2237402-2.jpg](https://images.zenhubusercontent.com/6011f2a9a91eae7cd6b405e5/66300fe0-a361-490b-b916-fd7239802df3)

**Comment by rhfallon** [comment]
https://teams.microsoft.com/_#/mp4/viewer/teams/https:~2F~2Fgtvault.sharepoint.com~2Fsites~2FJDF-0357JuniorDesignGroup~2FShared%20Documents~2FGeneral~2FScripts~2F2021-04-02%2017-58-37.mp4?threadId=19:8a278cd6bab148bdbe922989f8e7f8f7@thread.tacv2&baseUrl=https:~2F~2Fgtvault.sharepoint.com~2Fsites~2FJDF-0357JuniorDesignGroup&fileId=0a0bda14-683c-4107-a19f-a5627692820c&ctx=files&rootContext=items_view&viewerAction=view

(Couldn't upload file here since the quality was too high)
